# Tipos de datos en numpy

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# para ver el tipo de datos del array

In [ ]:
arr.dtype

dtype('int64')

#creamos un array y le pasamos el tipo de dato

In [ ]:
arr_float = np.array([1,2,3,4,5,6,7,8,9], dtype='float64')
arr_float

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
type(arr_float)

numpy.ndarray

In [ ]:
arr_float.dtype

dtype('float64')

# CONVERTIR TIPOS DE DATOS

In [ ]:
arr = np.array([1,0,3,4])
arr_bool = arr.astype(np.bool_)
arr_bool

array([ True, False,  True,  True])

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr_str = arr.astype(np.bytes_)
arr_str

array([b'1', b'0', b'3', b'4'], dtype='|S21')