# FUNCIONES MAS COMUNES EN NUMPY

In [1]:
import numpy as np

# SHAPE Y RESHAPE

In [2]:
arr = np.random.randint(1,10,(3,2))
arr

array([[8, 1],
       [3, 3],
       [6, 2]])

In [3]:
arr.shape

(3, 2)

In [4]:
arr.ndim

2

In [5]:
arr.reshape(1,6)

array([[8, 1, 3, 3, 6, 2]])

In [6]:
arr.ndim

2

# MAX Y ARGMAX

In [7]:
arr = np.random.randint(1,20,10)
arr

array([ 6, 16,  6,  8, 11, 12,  5,  1, 11, 15])

In [8]:
matriz = arr.reshape(2,5)
matriz

array([[ 6, 16,  6,  8, 11],
       [12,  5,  1, 11, 15]])

In [9]:
arr.max()

np.int64(16)

In [10]:
matriz.max()

np.int64(16)

In [11]:
arr.argmax()

np.int64(1)

# MIN Y ARGMIN

In [12]:
arr.min()

np.int64(1)

In [13]:
matriz.min()

np.int64(1)

In [15]:
matriz.min(0)

array([ 6,  5,  1,  8, 11])

# SORT

In [16]:
arr

array([ 6, 16,  6,  8, 11, 12,  5,  1, 11, 15])

In [17]:
arr.sort()
arr

array([ 1,  5,  6,  6,  8, 11, 11, 12, 15, 16])